#! /bin/bash
if [[ $EUID -ne 0 ]]; then
   echo "You must be root to run this script." 1>&2
   exit 100
fi
dpkg --get-selections|grep 'linux-image*'|awk '{print $1}'|egrep -v "linux-image-$(uname -r)|linux-image-generic" |while read n;do apt-get -y remove $n;done
apt-get --purge autoremove 
apt-get autoclean &&  apt-get clean all
apt-get purge $(dpkg -l | awk '/^rc/ { print $2 }')
exit 0
