#!/bin/bash 
openssl=$(which openssl)
echo "If you intent to encrypt a file owned by root (or any other than you), 
run this script as root or it will fail, despite the stdout messages"
sleep 3
echo "" 
echo "Please give the absolute path of the file you want to encrypt"
read file
$openssl aes-128-cbc -salt -in $file -out $file.aes
if [[ $? -ne 0 ]]; then
   exit 100
else
   echo "Your file has been encrypted as $file.aes"
fi
sleep 1
echo ""
echo "Do you want to delete the original file? (yes/no)" 
read answer
if [[ $answer = "yes" ]]; then
   /bin/rm $file
   echo "The original file has been deleted"
else
   echo "The original file in not deleted"
exit 0
fi
